import { jsPDF } from 'jspdf'
import type { Question } from '@/api/types'

export interface QuestionSection {
  heading: string
  questions: Question[]
}

const BRAND = {
  emerald: [5, 150, 105] as [number, number, number],   // #059669
  emeraldDark: [4, 120, 87] as [number, number, number], // #047857
  text: [17, 24, 39] as [number, number, number],         // #111827
  muted: [107, 114, 128] as [number, number, number],     // #6B7280
  divider: [229, 231, 235] as [number, number, number],   // #E5E7EB
}

const A4 = { width: 210, height: 297 } // mm
const MARGIN = { top: 18, bottom: 16, left: 16, right: 16 }
const CONTENT_WIDTH = A4.width - MARGIN.left - MARGIN.right

// ─────────────────────────────────────────────────────────────────────────────
// Math/symbol sanitisation: jsPDF's default core fonts are Latin-1 only and
// will render unicode like √, π, ², ÷ as "?". Convert the most common math
// notation to ASCII equivalents that read clearly on paper.
// ─────────────────────────────────────────────────────────────────────────────
function stripLatex(s: string): string {
  if (!s) return ''
  return s
    // KaTeX/LaTeX delimiters
    .replace(/\$\$([^$]+)\$\$/g, '$1')
    .replace(/\$([^$]+)\$/g, '$1')
    // Common LaTeX commands
    .replace(/\\frac\s*\{([^{}]+)\}\s*\{([^{}]+)\}/g, '($1)/($2)')
    .replace(/\\sqrt\s*\{([^{}]+)\}/g, 'sqrt($1)')
    .replace(/\\sqrt\s*([a-zA-Z0-9])/g, 'sqrt($1)')
    .replace(/\\times/g, ' x ')
    .replace(/\\div/g, ' / ')
    .replace(/\\cdot/g, '.')
    .replace(/\\pi/g, 'pi')
    .replace(/\\theta/g, 'theta')
    .replace(/\\alpha/g, 'alpha')
    .replace(/\\beta/g, 'beta')
    .replace(/\\gamma/g, 'gamma')
    .replace(/\\delta/g, 'delta')
    .replace(/\\sum/g, 'sum')
    .replace(/\\int/g, 'integral')
    .replace(/\\infty/g, 'infinity')
    .replace(/\\leq/g, '<=')
    .replace(/\\geq/g, '>=')
    .replace(/\\neq/g, '!=')
    .replace(/\\approx/g, '~=')
    .replace(/\\degree/g, ' deg')
    .replace(/\^\{([^{}]+)\}/g, '^($1)')
    .replace(/_\{([^{}]+)\}/g, '_($1)')
    .replace(/\{([^{}]+)\}/g, '$1')
    .replace(/\\\\/g, ' ')
    // Replace common unicode math with ASCII so jsPDF can render it
    .replace(/√/g, 'sqrt')
    .replace(/π/g, 'pi')
    .replace(/θ/g, 'theta')
    .replace(/α/g, 'alpha')
    .replace(/β/g, 'beta')
    .replace(/γ/g, 'gamma')
    .replace(/δ/g, 'delta')
    .replace(/Σ/g, 'sum')
    .replace(/∫/g, 'integral')
    .replace(/∞/g, 'infinity')
    .replace(/≤/g, '<=')
    .replace(/≥/g, '>=')
    .replace(/≠/g, '!=')
    .replace(/×/g, 'x')
    .replace(/÷/g, '/')
    .replace(/°/g, ' deg')
    .replace(/²/g, '^2')
    .replace(/³/g, '^3')
    .replace(/[‘’]/g, "'")
    .replace(/[“”]/g, '"')
    .replace(/[–—]/g, '-')
    .replace(/ /g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
}

function letterOf(index: number) {
  return String.fromCharCode(65 + index)
}

// ─────────────────────────────────────────────────────────────────────────────
// PDF building blocks
// ─────────────────────────────────────────────────────────────────────────────
function drawHeader(doc: jsPDF, title: string, subtitle: string) {
  // Emerald brand bar
  doc.setFillColor(...BRAND.emerald)
  doc.rect(0, 0, A4.width, 12, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(13)
  doc.text('BroxStudies', MARGIN.left, 8)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8)
  doc.text('WAEC • WASSCE • NAPTEX preparation', A4.width - MARGIN.right, 8, { align: 'right' })

  // Document title
  doc.setTextColor(...BRAND.text)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(16)
  doc.text(title, MARGIN.left, 22)

  if (subtitle) {
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(10)
    doc.setTextColor(...BRAND.muted)
    doc.text(subtitle, MARGIN.left, 28)
  }

  // Divider
  doc.setDrawColor(...BRAND.divider)
  doc.setLineWidth(0.3)
  doc.line(MARGIN.left, 32, A4.width - MARGIN.right, 32)
}

function drawFooter(doc: jsPDF, page: number, total: number) {
  doc.setDrawColor(...BRAND.divider)
  doc.setLineWidth(0.2)
  doc.line(MARGIN.left, A4.height - MARGIN.bottom + 4, A4.width - MARGIN.right, A4.height - MARGIN.bottom + 4)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8)
  doc.setTextColor(...BRAND.muted)
  doc.text('Generated by BroxStudies — broxstudies.com', MARGIN.left, A4.height - MARGIN.bottom + 9)
  doc.text(`Page ${page} of ${total}`, A4.width - MARGIN.right, A4.height - MARGIN.bottom + 9, { align: 'right' })
}

interface Cursor { y: number; page: number }

function ensureSpace(doc: jsPDF, cursor: Cursor, needed: number, drawHeaderFn: () => void) {
  if (cursor.y + needed > A4.height - MARGIN.bottom) {
    doc.addPage()
    cursor.page += 1
    drawHeaderFn()
    cursor.y = 36
  }
}

function writeWrapped(
  doc: jsPDF,
  text: string,
  x: number,
  cursor: Cursor,
  maxWidth: number,
  lineHeight: number,
  drawHeaderFn: () => void,
): number {
  const lines = doc.splitTextToSize(text, maxWidth) as string[]
  for (const line of lines) {
    ensureSpace(doc, cursor, lineHeight, drawHeaderFn)
    doc.text(line, x, cursor.y)
    cursor.y += lineHeight
  }
  return lines.length
}

// ─────────────────────────────────────────────────────────────────────────────
// Public API
// ─────────────────────────────────────────────────────────────────────────────
export function downloadQuestionsAsPDF(
  title: string,
  subtitle: string,
  sections: QuestionSection[],
  filename: string,
) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })

  const drawCurrentHeader = () => drawHeader(doc, title, subtitle)
  drawCurrentHeader()

  const cursor: Cursor = { y: 40, page: 1 }

  for (const section of sections) {
    if (!section.questions.length) continue

    // Section heading
    ensureSpace(doc, cursor, 14, drawCurrentHeader)
    doc.setFillColor(...BRAND.emeraldDark)
    doc.rect(MARGIN.left, cursor.y - 4, CONTENT_WIDTH, 7, 'F')
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(11)
    doc.setTextColor(255, 255, 255)
    doc.text(stripLatex(section.heading), MARGIN.left + 2, cursor.y + 1)
    cursor.y += 10

    // Questions
    section.questions.forEach((q, idx) => {
      const number = idx + 1
      ensureSpace(doc, cursor, 12, drawCurrentHeader)

      // Question stem
      doc.setFont('helvetica', 'bold')
      doc.setFontSize(10)
      doc.setTextColor(...BRAND.text)
      writeWrapped(
        doc,
        `${number}. ${stripLatex(q.question_text)}`,
        MARGIN.left,
        cursor,
        CONTENT_WIDTH,
        5,
        drawCurrentHeader,
      )
      cursor.y += 1

      // Options (MCQ)
      if (q.options?.length) {
        doc.setFont('helvetica', 'normal')
        doc.setFontSize(10)
        doc.setTextColor(...BRAND.text)
        q.options.forEach((opt, oi) => {
          writeWrapped(
            doc,
            `${letterOf(oi)}. ${stripLatex(opt)}`,
            MARGIN.left + 6,
            cursor,
            CONTENT_WIDTH - 6,
            5,
            drawCurrentHeader,
          )
        })
      }

      // Answer
      if (q.correct_answer) {
        cursor.y += 1
        doc.setFont('helvetica', 'bold')
        doc.setFontSize(9)
        doc.setTextColor(...BRAND.emeraldDark)
        writeWrapped(
          doc,
          `Answer: ${stripLatex(q.correct_answer)}`,
          MARGIN.left,
          cursor,
          CONTENT_WIDTH,
          4.5,
          drawCurrentHeader,
        )
      }

      // Explanation
      if (q.explanation) {
        doc.setFont('helvetica', 'italic')
        doc.setFontSize(9)
        doc.setTextColor(...BRAND.muted)
        writeWrapped(
          doc,
          `Explanation: ${stripLatex(q.explanation)}`,
          MARGIN.left,
          cursor,
          CONTENT_WIDTH,
          4.5,
          drawCurrentHeader,
        )
      }

      cursor.y += 4
    })

    cursor.y += 2
  }

  // Footers on every page
  const totalPages = doc.getNumberOfPages()
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i)
    drawFooter(doc, i, totalPages)
  }

  doc.save(filename)
}

export function buildShareText(title: string, sections: QuestionSection[]): string {
  const parts: string[] = [title, '='.repeat(title.length), '']
  for (const section of sections) {
    if (!section.questions.length) continue
    parts.push(section.heading)
    parts.push('-'.repeat(section.heading.length))
    section.questions.forEach((q, i) => {
      parts.push(`${i + 1}. ${stripLatex(q.question_text)}`)
      if (q.options?.length) {
        q.options.forEach((opt, oi) => parts.push(`   ${letterOf(oi)}. ${stripLatex(opt)}`))
      }
      if (q.correct_answer) parts.push(`   Answer: ${stripLatex(q.correct_answer)}`)
      if (q.explanation) parts.push(`   Explanation: ${stripLatex(q.explanation)}`)
      parts.push('')
    })
  }
  parts.push('Generated by BroxStudies — broxstudies.com')
  return parts.join('\n')
}

export async function shareOrCopy(text: string, title: string): Promise<'shared' | 'copied'> {
  if (navigator.share) {
    try {
      await navigator.share({ title, text })
      return 'shared'
    } catch {
      // user cancelled or API unavailable — fall through
    }
  }
  await navigator.clipboard.writeText(text)
  return 'copied'
}
